steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'us-central1-docker.pkg.dev/semiotic-vial-255604/workshop/spatial:alpha', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/semiotic-vial-255604/workshop/spatial:alpha']
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 9600s
